import { CanonicalStateBadge, DataClassificationBadge, DemoDataBadge } from '../components/data-integrity/Badges'
import { GlassSurface } from '../visuals/glass/GlassSurface'

export function AdminPage() {
  return (
    <div className="space-y-6">
      <header className="role-hero role-hero--admin rounded-2xl border border-white/10 p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="flex gap-2"><DemoDataBadge /><span className="rounded-md border border-white/12 bg-white/5 px-2 py-1 text-[0.62rem] font-bold tracking-[0.12em] text-slate-300">ADMIN</span></div><p className="section-kicker mt-5">Platform operations</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.035em] text-white sm:text-4xl">System health & exceptions</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Monitor offline demo adapters, dataset registration, manual-review items, and audit continuity.</p></div><CanonicalStateBadge state="DEMO_MODE" /></div></header>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Administration summary">{[['Adapters', '3 / 3', 'Sandbox services available'], ['Datasets', '01', 'Local fixture registered'], ['Exceptions', '01', 'Manual review required'], ['Audit chain', '04', 'Linked demo events']].map(([label, value, detail]) => <GlassSurface as="article" key={label} className="p-5"><div className="flex justify-between gap-3"><p className="text-xs text-slate-400">{label}</p><DataClassificationBadge classification="SIMULATED" /></div><p className="mt-4 font-mono text-2xl font-semibold text-white">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></GlassSurface>)}</section>
      <div className="grid gap-6 xl:grid-cols-[1fr_1fr]">
        <section className="surface-card p-5 sm:p-6" aria-labelledby="adapter-heading"><p className="section-kicker">Replaceable integrations</p><h2 id="adapter-heading" className="section-title">Adapter health</h2><div className="mt-5 space-y-3">{[['HistoricalCSVProvider', 'READY', 'Local verified fixture'], ['InsurerSandboxAdapter', 'READY', 'No external insurer connection'], ['LenderSandboxAdapter', 'READY', 'No money movement']].map(([name, status, detail]) => <div key={name} className="flex items-center justify-between gap-4 rounded-xl border border-white/7 bg-deep/45 p-4"><div><p className="font-mono text-xs font-semibold text-slate-300">{name}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div><CanonicalStateBadge state={status} /></div>)}</div></section>
        <section className="surface-card p-5 sm:p-6" aria-labelledby="dataset-heading"><p className="section-kicker">Offline reproducibility</p><h2 id="dataset-heading" className="section-title">Dataset registry</h2><div className="mt-5 rounded-xl border border-white/7 bg-deep/45 p-5"><div className="flex justify-between gap-3"><div><p className="text-sm font-semibold text-slate-300">Surat rainfall replay fixture</p><p className="mt-1 font-mono text-[0.65rem] text-slate-600">DS-MC-RAIN-2026-01</p></div><DataClassificationBadge classification="SIMULATED" /></div><dl className="mt-5 grid grid-cols-2 gap-4"><div><dt className="text-xs text-slate-500">Checksum</dt><dd className="mt-1 font-mono text-[0.68rem] text-slate-300">sha256: 8fa…27c</dd></div><div><dt className="text-xs text-slate-500">Validation</dt><dd className="mt-1 text-xs font-semibold text-teal">PASSED</dd></div></dl></div></section>
      </div>
      <section className="rounded-2xl border border-danger/25 bg-danger/7 p-5 sm:p-6" aria-labelledby="admin-exception-heading"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="section-kicker text-danger/65">MC-EXC-0007</p><h2 id="admin-exception-heading" className="mt-2 text-lg font-semibold text-danger">Lender receipt missing</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Insurer sandbox reports ₹25,000 paid; lender sandbox has no matching receipt. Source records are preserved and the item remains in manual review.</p></div><CanonicalStateBadge state="IN_REVIEW" /></div></section>
    </div>
  )
}
