import { CanonicalStateBadge, DataClassificationBadge, DemoDataBadge } from '../components/data-integrity/Badges'
import { GlassSurface } from '../visuals/glass/GlassSurface'

export function BorrowerExperiencePage() {
  return (
    <div className="mx-auto max-w-4xl space-y-6">
      <header className="role-hero role-hero--borrower overflow-hidden rounded-[1.4rem] border border-white/10 p-6 sm:p-9"><div className="max-w-2xl"><div className="flex gap-2"><DemoDataBadge /><DataClassificationBadge classification="SIMULATED" /></div><p className="section-kicker mt-6">Hello, ABC Textiles</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-white sm:text-5xl">Your climate cover is active.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-slate-300/80">We are monitoring your demo coverage window. A recent event is being reviewed independently by the insurer sandbox.</p></div></header>

      <section className="rounded-2xl border border-amber/25 bg-amber/7 p-5 sm:p-6" aria-labelledby="borrower-event-heading"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="section-kicker text-amber/65">Event update</p><h2 id="borrower-event-heading" className="mt-2 text-lg font-semibold text-amber">Review in progress</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Rainfall information met the demo review threshold. This does not mean a payment has been approved. We will update this page after the insurer sandbox decides.</p></div><CanonicalStateBadge state="TRIGGER_CANDIDATE" /></div></section>

      <div className="grid gap-6 md:grid-cols-2">
        <GlassSurface as="section" tint="teal" className="p-5 sm:p-6" aria-labelledby="borrower-cover-heading"><div className="flex justify-between gap-3"><div><p className="section-kicker">Coverage summary</p><h2 id="borrower-cover-heading" className="section-title">What you accepted</h2></div><CanonicalStateBadge state="ACTIVE" /></div><dl className="mt-6 space-y-4">{[['Covered event', 'Extreme rainfall'], ['Coverage period', '15 Jun – 30 Sep 2026'], ['Illustrative benefit', 'Up to ₹40,000'], ['Reference', 'MC-PS-2026-0142-v1']].map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b border-white/6 pb-3 last:border-0"><dt className="text-xs text-slate-500">{label}</dt><dd className="text-right text-xs font-semibold text-slate-300">{value}</dd></div>)}</dl><div className="mt-5 rounded-xl border border-teal/20 bg-teal/6 p-4"><p className="text-xs font-semibold text-teal">Consent recorded</p><p className="mt-1 text-xs text-slate-500">15 Jun 2026 · English · Web demo</p></div></GlassSurface>
        <section className="surface-card p-5 sm:p-6" aria-labelledby="borrower-journey-heading"><p className="section-kicker">Current journey</p><h2 id="borrower-journey-heading" className="section-title">What happens next</h2><ol className="mt-6 space-y-4">{[['1', 'Insurer review', 'Independent sandbox decision pending'], ['2', 'If approved', 'MonsoonCover routes an illustrative instruction'], ['3', 'Lender posting', 'Lender sandbox records the amount'], ['4', 'Confirmation', 'Records must reconcile before completion']].map(([step, title, copy]) => <li key={step} className="grid grid-cols-[2rem_1fr] gap-3"><span className="grid size-8 place-items-center rounded-full border border-cyan/20 bg-cyan/6 font-mono text-xs text-cyan">{step}</span><div><p className="text-sm font-semibold text-slate-300">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy}</p></div></li>)}</ol></section>
      </div>

      <section className="surface-card p-5 sm:p-6" aria-labelledby="basis-risk-heading"><p className="section-kicker">Important disclosure</p><h2 id="basis-risk-heading" className="section-title">How parametric cover differs</h2><p className="mt-4 text-sm leading-6 text-slate-400">A payment depends on the defined data and trigger terms, not an assessment of your exact business loss. You may experience loss without the trigger being met, or the trigger may be met when your loss differs from the benefit.</p><p className="mt-3 text-xs leading-5 text-slate-600">This is a synthetic demonstration, not financial advice or a real insurance contract.</p></section>
    </div>
  )
}
