"""settlement chain tables

Revision ID: 0ac002d2bd0e
Revises: f3363eb5d924
Create Date: 2026-09-03 23:08:32.457193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac002d2bd0e'
down_revision: Union[str, None] = 'f3363eb5d924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exception_cases',
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('case_reference', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('detail', sa.String(length=2048), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'CANCELLED', name='exception_state'), nullable=False),
    sa.Column('opened_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_method', sa.String(length=512), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_reference')
    )
    op.create_index(op.f('ix_exception_cases_correlation_id'), 'exception_cases', ['correlation_id'], unique=False)
    op.create_table('insurer_requests',
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('external_request_id', sa.String(length=255), nullable=False),
    sa.Column('submitted_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('adapter_name', sa.String(length=128), nullable=False),
    sa.Column('adapter_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['trigger_evaluations.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['borrower_policy_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_insurer_requests_correlation_id'), 'insurer_requests', ['correlation_id'], unique=False)
    op.create_table('insurer_decisions',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'NEEDS_MORE_DATA', 'APPROVED', 'REJECTED', name='insurer_decision_outcome'), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=False),
    sa.Column('decided_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['insurer_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurer_decisions_correlation_id'), 'insurer_decisions', ['correlation_id'], unique=False)
    op.create_table('payouts',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payout_reference', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('state', sa.Enum('NOT_APPLICABLE', 'APPROVED', 'INITIATED', 'PAID', 'FAILED', name='payout_state'), nullable=False),
    sa.Column('initiated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['insurer_decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('payout_reference')
    )
    op.create_index(op.f('ix_payouts_correlation_id'), 'payouts', ['correlation_id'], unique=False)
    op.create_table('lender_postings',
    sa.Column('payout_id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('external_posting_id', sa.String(length=255), nullable=False),
    sa.Column('payout_reference', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('state', sa.Enum('NOT_REQUESTED', 'PENDING', 'RECEIVED', 'POSTED', 'FAILED', name='lender_posting_state'), nullable=False),
    sa.Column('posted_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_lender_postings_correlation_id'), 'lender_postings', ['correlation_id'], unique=False)
    op.create_table('reconciliation_records',
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('payout_id', sa.String(length=36), nullable=False),
    sa.Column('posting_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.Enum('NOT_READY', 'PENDING', 'RECONCILED', 'MISMATCH', name='reconciliation_state'), nullable=False),
    sa.Column('insurer_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lender_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('difference_reason', sa.String(length=1024), nullable=True),
    sa.Column('reconciled_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['lender_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_records_correlation_id'), 'reconciliation_records', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_records_correlation_id'), table_name='reconciliation_records')
    op.drop_table('reconciliation_records')
    op.drop_index(op.f('ix_lender_postings_correlation_id'), table_name='lender_postings')
    op.drop_table('lender_postings')
    op.drop_index(op.f('ix_payouts_correlation_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_insurer_decisions_correlation_id'), table_name='insurer_decisions')
    op.drop_table('insurer_decisions')
    op.drop_index(op.f('ix_insurer_requests_correlation_id'), table_name='insurer_requests')
    op.drop_table('insurer_requests')
    op.drop_index(op.f('ix_exception_cases_correlation_id'), table_name='exception_cases')
    op.drop_table('exception_cases')
    # ### end Alembic commands ###
