"""evidence registry

Revision ID: 23290b2a1f60
Revises: c5b10d749d22
Create Date: 2026-09-04 00:38:59.048684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23290b2a1f60'
down_revision: Union[str, None] = 'c5b10d749d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_records',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=128), nullable=False),
    sa.Column('subject_field', sa.String(length=128), nullable=False),
    sa.Column('value_or_claim', sa.String(length=1024), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('source_title', sa.String(length=512), nullable=True),
    sa.Column('source_organization', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=128), nullable=True),
    sa.Column('source_url_or_local_path', sa.String(length=1024), nullable=True),
    sa.Column('publication_or_effective_date', sa.String(length=64), nullable=True),
    sa.Column('accessed_or_verified_at', sa.String(length=64), nullable=True),
    sa.Column('geographic_scope', sa.String(length=255), nullable=True),
    sa.Column('applicability_scope', sa.String(length=512), nullable=True),
    sa.Column('units', sa.String(length=64), nullable=True),
    sa.Column('transformation_or_formula', sa.String(length=1024), nullable=True),
    sa.Column('simulation_reason', sa.String(length=1024), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('used_by', sa.String(length=512), nullable=True),
    sa.Column('review_status', sa.String(length=64), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.Column('registered_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_records')
    # ### end Alembic commands ###
