"""risk assessment and policy eligibility

Revision ID: c5b10d749d22
Revises: 0ac002d2bd0e
Create Date: 2026-09-04 00:24:53.297103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b10d749d22'
down_revision: Union[str, None] = '0ac002d2bd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_eligibilities',
    sa.Column('borrower_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('matching_version', sa.String(length=64), nullable=False),
    sa.Column('evaluated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('borrower_id', 'policy_version_id', name='uq_eligibility_borrower_policy')
    )
    op.create_table('risk_assessments',
    sa.Column('borrower_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=128), nullable=False),
    sa.Column('peril', sa.String(length=64), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=False),
    sa.Column('exposure_band', sa.Enum('LOW', 'MODERATE', 'HIGH', name='exposure_band'), nullable=False),
    sa.Column('max_daily_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('heavy_day_count', sa.Integer(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('normalized_unit', sa.String(length=32), nullable=False),
    sa.Column('methodology_version', sa.String(length=64), nullable=False),
    sa.Column('methodology_steps', sa.JSON(), nullable=False),
    sa.Column('dataset_code', sa.String(length=128), nullable=False),
    sa.Column('assessed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default is required so this NOT NULL column can be added to a
    # table that already holds rows; existing borrowers become UNZONED and
    # must be assigned a real zone before policy matching can succeed.
    op.add_column(
        'borrowers',
        sa.Column('zone_id', sa.String(length=128), nullable=False, server_default='UNZONED'),
    )
    op.add_column('borrowers', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('borrowers', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowers', 'longitude')
    op.drop_column('borrowers', 'latitude')
    op.drop_column('borrowers', 'zone_id')
    op.drop_table('risk_assessments')
    op.drop_table('policy_eligibilities')
    # ### end Alembic commands ###
