"""initial schema

Revision ID: df4ff8e3e4c1
Revises: 
Create Date: 2026-09-03 22:09:35.198813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4ff8e3e4c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('occurred_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('previous_state', sa.String(length=255), nullable=True),
    sa.Column('new_state', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('request_or_evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('application_version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_table('borrowers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'idempotency_key', name='uq_idempotency_scope_key')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('LENDER', 'INSURER', 'BORROWER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('loans',
    sa.Column('borrower_id', sa.String(length=36), nullable=False),
    sa.Column('loan_type', sa.String(length=255), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('idempotency_records')
    op.drop_table('borrowers')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
