"""climate policy and trigger tables

Revision ID: f3363eb5d924
Revises: df4ff8e3e4c1
Create Date: 2026-09-03 23:00:57.061107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3363eb5d924'
down_revision: Union[str, None] = 'df4ff8e3e4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_datasets',
    sa.Column('dataset_code', sa.String(length=128), nullable=False),
    sa.Column('source_organization', sa.String(length=255), nullable=False),
    sa.Column('source_uri_or_document', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('accessed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geographic_coverage', sa.String(length=512), nullable=False),
    sa.Column('temporal_coverage', sa.String(length=255), nullable=False),
    sa.Column('parameter_definitions', sa.String(length=1024), nullable=False),
    sa.Column('original_sha256', sa.String(length=64), nullable=False),
    sa.Column('transformation_version', sa.String(length=64), nullable=False),
    sa.Column('known_gaps_or_caveats', sa.String(length=2048), nullable=True),
    sa.Column('license_notes', sa.String(length=1024), nullable=True),
    sa.Column('source_classification', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_code')
    )
    op.create_table('policy_versions',
    sa.Column('product_code', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('trigger_rule', sa.JSON(), nullable=False),
    sa.Column('disclosure_version', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code', 'version', name='uq_policy_product_version')
    )
    op.create_table('climate_observations',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('provider_record_id', sa.String(length=255), nullable=False),
    sa.Column('source_classification', sa.String(length=32), nullable=False),
    sa.Column('source_uri_or_file', sa.String(length=1024), nullable=False),
    sa.Column('ingested_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_timezone', sa.String(length=64), nullable=False),
    sa.Column('policy_local_date', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('zone_id', sa.String(length=128), nullable=False),
    sa.Column('parameter', sa.String(length=64), nullable=False),
    sa.Column('raw_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('raw_unit', sa.String(length=32), nullable=False),
    sa.Column('normalized_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('normalized_unit', sa.String(length=32), nullable=False),
    sa.Column('quality_status', sa.Enum('RAW', 'NORMALIZED', 'VALIDATED', 'VERIFIED_REFERENCE_DATA', 'REJECTED', name='observation_quality_status'), nullable=False),
    sa.Column('processing_version', sa.String(length=64), nullable=False),
    sa.Column('checksum_or_source_hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['climate_datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_record_id', name='uq_observation_provider_record')
    )
    op.create_table('borrower_policy_snapshots',
    sa.Column('snapshot_reference', sa.String(length=128), nullable=False),
    sa.Column('borrower_id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_rule_snapshot', sa.JSON(), nullable=False),
    sa.Column('disclosure_version', sa.String(length=32), nullable=False),
    sa.Column('consent_recorded_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_checksum', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('PENDING_ISSUANCE', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'CANCELLED', name='policy_state'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_reference')
    )
    op.create_table('trigger_evaluations',
    sa.Column('evaluation_key', sa.String(length=255), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.Enum('NO_TRIGGER', 'NEAR_TRIGGER', 'TRIGGER_CANDIDATE', name='trigger_outcome'), nullable=False),
    sa.Column('observed_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('strike_threshold', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('normalized_unit', sa.String(length=32), nullable=False),
    sa.Column('window_start_local', sa.String(length=10), nullable=False),
    sa.Column('window_end_local', sa.String(length=10), nullable=False),
    sa.Column('evaluated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluation_version', sa.String(length=64), nullable=False),
    sa.Column('observation_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['borrower_policy_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_key')
    )
    op.create_index(op.f('ix_trigger_evaluations_correlation_id'), 'trigger_evaluations', ['correlation_id'], unique=False)
    op.create_table('calculation_traces',
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('inputs_digest', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['trigger_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_traces')
    op.drop_index(op.f('ix_trigger_evaluations_correlation_id'), table_name='trigger_evaluations')
    op.drop_table('trigger_evaluations')
    op.drop_table('borrower_policy_snapshots')
    op.drop_table('climate_observations')
    op.drop_table('policy_versions')
    op.drop_table('climate_datasets')
    # ### end Alembic commands ###
